// Auto-generated by erc8004-indexer — do not edit manually
import type { APIRoute } from "astro";

const agentIndex = {
  "lastAgentId": 56,
  "indexedAt": "2026-03-19T20:36:47.565Z",
  "network": "mainnet",
  "agents": [
    {
      "agentId": 1,
      "owner": "SP2GHQRCRMYY4S8PMBR49BEKX144VR437YT42SF3B",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 2,
      "owner": "SP13H2T1D1DS5MGP68GD6MEVRAW0RCJ3HBCMPX30Y",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 3,
      "owner": "SPKH9AWG0ENZ87J1X0PBD4HETP22G8W22AFNVF8K",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 4,
      "owner": "SP16H0KE0BPR4XNQ64115V5Y1V3XTPGMWG5YPC9TR",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 5,
      "owner": "SP4DXVEC16FS6QR7RBKGWZYJKTXPC81W49W0ATJE",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 6,
      "owner": "SP3YFNED181E67KH2MC7KNCJ24ABE8C3W5JG17M0V",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 7,
      "owner": "SP2BY809C843KKT3NNF02HFKB9BJPM65Z08AY7RTY",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 8,
      "owner": "SP22G05KW9JVDV5BAN8B7EJWYBNCY332D1Q30DDBD",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 9,
      "owner": "SP9NVXH7DJMDH0X3NM5H5WNE0T5S8YYKTTFVKSTM",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 10,
      "owner": "SPG6VGJ5GTG5QKBV2ZV03219GSGH37PJGXQYXP47",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 11,
      "owner": "SP1JBH94STS4MHD61H3HA1ZN2R4G41EZGFG9SXP66",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 12,
      "owner": "SP105KWW31Y89F5AZG0W7RFANQGRTX3XW0VR1CX2M",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 13,
      "owner": "SP1RHDCCVQ3SVV2DRSP2PJNXJCA12QE72W5C7EMFS",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 14,
      "owner": "SP16WDGQ84GQWKWT9562M7RDPS6ZJWJBN9PFN27RW",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 15,
      "owner": "SP3DVRQ8BZB108AJXPXD0SXJ3S210M7NHG3FM3CT4",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 16,
      "owner": "SP8KCB9KXP0ZRMMAJNP7E8QRYYXC9YDT31TFNAMS",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 17,
      "owner": "SP17XV7ZX2ZVM62YV8X0TS2QQS8Q3S928K7FMVM0B",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 18,
      "owner": "SP3QVGQG4SFHP0C983N1Y49V27CA70D2Y46E5Q4ZT",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 19,
      "owner": "SP38GBJ8GCXNKNNC87R5AZEPW7K6A1SSD6E1D6VNH",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 20,
      "owner": "SP16WDGQ84GQWKWT9562M7RDPS6ZJWJBN9PFN27RW",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 21,
      "owner": "SP16WDGQ84GQWKWT9562M7RDPS6ZJWJBN9PFN27RW",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 22,
      "owner": "SP2P7SPX26TNTWXFHGSQ682KQWG6GGSBVV4W409B",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 23,
      "owner": "SP1SNJB17YQN84BHFCP82CNK237HGHM1N401W5CSF",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 24,
      "owner": "SP1NM9RBG706BM4KJQJ5CAYRC2CGT738PVBVVDZNN",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 25,
      "owner": "SP3N5Z4AX97ZCDPZMAHA5S8G6A68Q515V2Y6S4TPD",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 26,
      "owner": "SP8H8V60E2ADRZ195ZTS47NJDC40TSRPA4A1TJG7",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 27,
      "owner": "SP15T1W26JTNS26VG17HM468KW7TQD3124KTYA9EJ",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 28,
      "owner": "SP2BY809C843KKT3NNF02HFKB9BJPM65Z08AY7RTY",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 29,
      "owner": "SP12Q1FS2DX4N8C2QYBM0Z2N2DY1EH9EEPMPH9N9X",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 30,
      "owner": "SP316ET3Z1JHH3G9KVQ9Q6HSX20FVV7TSD1J0EBWT",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 31,
      "owner": "SP316ET3Z1JHH3G9KVQ9Q6HSX20FVV7TSD1J0EBWT",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 32,
      "owner": "SPNTEKCYS2PWDKH92WFTAT66N0NJG45D01G7T9YR",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 33,
      "owner": "SPKH9AWG0ENZ87J1X0PBD4HETP22G8W22AFNVF8K",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 34,
      "owner": "SPG6VGJ5GTG5QKBV2ZV03219GSGH37PJGXQYXP47",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 35,
      "owner": "SPB3QD70F8JH7WTQ056DS2H5SYZEZ3ZXKES3D4ES",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 36,
      "owner": "SPGECM4AGGV6EE1QZS26XC66SDKPFHV6AK6GEDKX",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 37,
      "owner": "SP1AK5ZKGDFAPXDVT6T9HZPW5D2R4DJ6Z40PZ7MKR",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 38,
      "owner": "SP2G6TM8JCRNK6WSPQE8S86FP2W3A4FEVGZCCCQT8",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 39,
      "owner": "SP2GHQRCRMYY4S8PMBR49BEKX144VR437YT42SF3B",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 40,
      "owner": "SP2GHQRCRMYY4S8PMBR49BEKX144VR437YT42SF3B",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 41,
      "owner": "SP2GHQRCRMYY4S8PMBR49BEKX144VR437YT42SF3B",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 42,
      "owner": "SP2GHQRCRMYY4S8PMBR49BEKX144VR437YT42SF3B",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 43,
      "owner": "SP3CPCZAG3N4MJQC4FZFTBK2VQN31MV2DQ9DFTE6N",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 44,
      "owner": "SP3CPCZAG3N4MJQC4FZFTBK2VQN31MV2DQ9DFTE6N",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 45,
      "owner": "SP1BC4VGS89QQTCZBMKRQQQFHHJA0KAE6606YJA72",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 46,
      "owner": "SP1BFDFJ3P2TGKF3QN5Z6BTTSSDAG4EXHXZZAYZBM",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 47,
      "owner": "SP1BC4VGS89QQTCZBMKRQQQFHHJA0KAE6606YJA72",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 48,
      "owner": "SP1WPX34HAXW3JHMRZR88FNWA9AYRBCFCBT2JJVCM",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 49,
      "owner": "SP3CPCZAG3N4MJQC4FZFTBK2VQN31MV2DQ9DFTE6N",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 50,
      "owner": "SPG6VGJ5GTG5QKBV2ZV03219GSGH37PJGXQYXP47",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 51,
      "owner": "SP135QGVMF433BRMRHDY521E7M02RWDJPGAJ8ZN9Y",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 52,
      "owner": "SP135QGVMF433BRMRHDY521E7M02RWDJPGAJ8ZN9Y",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 53,
      "owner": "SP178SWBKE4YRKPMPBTFP359DMBT025ZC48QEG7HB",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 54,
      "owner": "SP2MPHJD7TM7CTNCZ55QT69AQYN7JEV6XM487700P",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 55,
      "owner": "SP1KGHF33817ZXW27CG50JXWC0Y6BNXAQ4E7YGAHM",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    },
    {
      "agentId": 56,
      "owner": "SP8KCB9KXP0ZRMMAJNP7E8QRYYXC9YDT31TFNAMS",
      "uri": null,
      "wallet": null,
      "network": "mainnet"
    }
  ]
} as const;

export const GET: APIRoute = () => {
  return new Response(JSON.stringify(agentIndex, null, 2), {
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600",
    },
  });
};

export const prerender = true;
