// Auto-generated by arc-catalog — do not edit manually
import type { APIRoute } from "astro";

const catalog = [
  {
    "name": "aibtc-dev-ops",
    "description": "Monitor service health via worker-logs and enforce production-grade standards across all aibtcdev repos",
    "tags": [
      "devops",
      "monitoring",
      "github",
      "aibtcdev"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 240,
    "category": "AIBTC Platform"
  },
  {
    "name": "aibtc-heartbeat",
    "description": "Signed AIBTC platform check-in every 5 minutes via BIP-137 Bitcoin message signing",
    "tags": [
      "aibtc",
      "heartbeat",
      "sensor"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 5,
    "category": "AIBTC Platform"
  },
  {
    "name": "aibtc-inbox-sync",
    "description": "Poll AIBTC platform inbox, sync messages locally, queue tasks for unread messages",
    "tags": [
      "comms",
      "aibtc",
      "inbox"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": true,
    "sensorInterval": 5,
    "category": "AIBTC Platform"
  },
  {
    "name": "aibtc-news-classifieds",
    "description": "Classified ads and extended API coverage for aibtc.news — list, post, and manage classifieds; read briefs; correct signals; update beats; fetch streaks and editorial resources",
    "tags": [
      "publishing",
      "news",
      "ai-btc",
      "commerce"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "AIBTC Platform"
  },
  {
    "name": "aibtc-news-deal-flow",
    "description": "Editorial voice for Deal Flow beat on aibtc.news — Real-time market signals, sats, Ordinals, bounties",
    "tags": [
      "publishing",
      "news",
      "ai-btc",
      "markets"
    ],
    "hasSensor": false,
    "hasCli": false,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "AIBTC Platform"
  },
  {
    "name": "aibtc-news-editorial",
    "description": "File intelligence signals, claim editorial beats, track correspondent activity on aibtc.news",
    "tags": [
      "publishing",
      "news",
      "ai-btc"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 360,
    "category": "AIBTC Platform"
  },
  {
    "name": "aibtc-repo-maintenance",
    "description": "Triage, review, test, and support aibtcdev repos we depend on",
    "tags": [
      "maintenance",
      "github",
      "aibtcdev"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 15,
    "category": "AIBTC Platform"
  },
  {
    "name": "arc-alive-check",
    "description": "Periodic system-alive task creator — 6-hour canary confirming dispatch loop is healthy",
    "tags": [
      "sensor",
      "system"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 360,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-architecture-review",
    "description": "Continuous architecture review, state machine diagrams, and simplification via SpaceX 5-step process",
    "tags": [
      "architecture",
      "simplification",
      "review"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 360,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-blocked-review",
    "description": "Sensor that periodically reviews blocked tasks to check if they can be unblocked",
    "tags": [
      "operations",
      "tasks"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 120,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-brand-voice",
    "description": "Brand identity consultant — voice rules, visual design system, content review",
    "tags": [
      "brand",
      "content",
      "publishing"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-catalog",
    "description": "Generate and publish skills/sensors catalog to arc0me-site",
    "tags": [
      "publishing",
      "meta",
      "skills"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 120,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-ceo-review",
    "description": "CEO reviews the latest watch report and actively manages the task queue",
    "tags": [],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": true,
    "sensorInterval": 240,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-ceo-strategy",
    "description": "Strategic operating manual — treat yourself as CEO of a one-entity company",
    "tags": [],
    "hasSensor": false,
    "hasCli": false,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-content-quality",
    "description": "Quality gate that checks content for AI writing patterns before publishing blog posts, X posts, and AIBTC signals",
    "tags": [
      "publishing",
      "quality",
      "content",
      "gate"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-cost-alerting",
    "description": "Monitor daily spend and alert when thresholds are exceeded — sensor-only, fires once per day at $30 default",
    "tags": [
      "monitoring",
      "cost"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 10,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-credentials",
    "description": "Encrypted credential store for API keys, tokens, and secrets used by other skills",
    "tags": [
      "secrets",
      "api-keys",
      "encryption"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-dispatch-evals",
    "description": "Dispatch quality evaluation — error analysis, LLM judges, calibration",
    "tags": [],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-email-sync",
    "description": "Sync email from arc-email-worker, detect unread messages, read and send email",
    "tags": [
      "comms",
      "email"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 1,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-failure-triage",
    "description": "Detect recurring failure patterns, escalate to investigation instead of retry",
    "tags": [
      "meta",
      "reliability"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 60,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-housekeeping",
    "description": "Periodic repo hygiene checks — uncommitted changes, stale locks, WAL size, memory bloat, file archival",
    "tags": [
      "infrastructure",
      "maintenance"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 30,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-link-research",
    "description": "Process batches of links into mission-relevant research reports — evaluates Bitcoin/AIBTC/Stacks relevance",
    "tags": [
      "research",
      "analysis"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-mcp-server",
    "description": "MCP server exposing Arc's task queue, skills, and memory to external Claude instances",
    "tags": [
      "mcp",
      "api",
      "integration"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-performance-analytics",
    "description": "Cost and token analytics by model tier, skill, and time period",
    "tags": [
      "analytics",
      "ops"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-report-email",
    "description": "Email watch reports when new ones are generated — sensor-only, fires after CEO review completes",
    "tags": [],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 5,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-reporting",
    "description": "Generate watch reports (HTML, 6-hour) and overnight briefs (markdown, daily 6am PST)",
    "tags": [],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": true,
    "sensorInterval": 60,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-reputation",
    "description": "Signed peer reviews with BIP-322 signatures, local SQLite storage, and give-feedback CLI",
    "tags": [
      "reputation",
      "signing",
      "l1"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 30,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-scheduler",
    "description": "Manages future task scheduling with deferred creation, overdue detection, and priority boost for past-due tasks",
    "tags": [
      "scheduling",
      "tasks",
      "core"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 5,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-self-audit",
    "description": "Daily operational self-audit — task queue health, cost trends, skill/sensor health, recent codebase changes",
    "tags": [
      "infrastructure",
      "monitoring",
      "daily"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 1440,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-service-health",
    "description": "System health monitor — detects stale cycles and stuck dispatch, triggers high-priority alerts",
    "tags": [
      "sensor",
      "system",
      "health"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 5,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-skill-manager",
    "description": "Create, inspect, and manage agent skills",
    "tags": [
      "meta",
      "skills",
      "scaffolding"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 120,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-starter-publish",
    "description": "Detect when v2 is ahead of main and merge/push to publish",
    "tags": [
      "meta",
      "git",
      "publishing"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 30,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-web-dashboard",
    "description": "Arc's live web dashboard — real-time task feed, sensor status, cost tracking",
    "tags": [],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-workflow-review",
    "description": "Detect repeating task patterns and propose workflow state machines — sensor creates P5 design tasks",
    "tags": [
      "orchestration",
      "workflows",
      "meta"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 240,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-workflows",
    "description": "Persistent state machine instances for multi-step workflows",
    "tags": [
      "orchestration",
      "state-management",
      "utilities"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 5,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc-worktrees",
    "description": "Opt-in git worktree isolation for high-risk dispatch tasks",
    "tags": [
      "isolation",
      "safety",
      "dispatch"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc0btc-ask-service",
    "description": "Handles paid Ask Arc questions submitted via /api/ask endpoint",
    "tags": [
      "monetization",
      "x402",
      "service"
    ],
    "hasSensor": false,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc0btc-monetization",
    "description": "Reviews Arc capabilities and surfaces monetizable service/product opportunities for arc0btc.com",
    "tags": [
      "strategy",
      "site"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": null,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc0btc-pr-review",
    "description": "Paid PR review service — accepts GitHub PR URLs via x402 payment and delivers structured code reviews",
    "tags": [
      "monetization",
      "github",
      "service"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 10,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arc0btc-site-health",
    "description": "Monitors arc0btc.com uptime, content freshness, API endpoints, and deployment status",
    "tags": [
      "sensor",
      "site",
      "monitoring"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 30,
    "category": "Arc Infrastructure"
  },
  {
    "name": "arxiv-research",
    "description": "Fetches and compiles arXiv papers on LLMs, agents, and AI into ISO-8601 research digests",
    "tags": [
      "research",
      "arxiv",
      "llm",
      "agents"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 720,
    "category": "Other"
  },
  {
    "name": "bitcoin-quorumclaw",
    "description": "Coordinate Bitcoin Taproot M-of-N multisig transactions via the QuorumClaw agent-multisig API. Handles agent registration, multisig creation, proposal submission, signing coordination, and broadcast.",
    "tags": [
      "l1",
      "mainnet-only",
      "sensitive"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 15,
    "category": "Bitcoin & Stacks"
  },
  {
    "name": "bitcoin-taproot-multisig",
    "description": "Bitcoin Taproot M-of-N multisig coordination — share pubkeys, verify co-signer signatures, and navigate the OP_CHECKSIGADD workflow.",
    "tags": [
      "l1",
      "mainnet-only",
      "sensitive"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Bitcoin & Stacks"
  },
  {
    "name": "bitcoin-wallet",
    "description": "Wallet management and cryptographic signing for Stacks and Bitcoin — unlock, lock, info, status, BTC/Stacks message signing, and BTC signature verification.",
    "tags": [
      "infrastructure",
      "sensitive",
      "signing"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Bitcoin & Stacks"
  },
  {
    "name": "blog-deploy",
    "description": "Auto-deploy arc0me-site to Cloudflare Workers on content changes",
    "tags": [
      "deployment",
      "cloudflare",
      "blog"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 5,
    "category": "Publishing & Social"
  },
  {
    "name": "blog-publishing",
    "description": "Create, manage, and publish blog posts with ISO8601 content pattern",
    "tags": [
      "publishing",
      "blogging",
      "content"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 60,
    "category": "Publishing & Social"
  },
  {
    "name": "claude-code-releases",
    "description": "Applicability research on new Claude Code releases — how each release affects Arc, AIBTC, and agents in general",
    "tags": [
      "research",
      "monitoring",
      "claude-code"
    ],
    "hasSensor": false,
    "hasCli": false,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Other"
  },
  {
    "name": "compliance-review",
    "description": "Audits all skills and sensors for structural, interface, and naming compliance with Arc conventions",
    "tags": [
      "housekeeping",
      "quality"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 360,
    "category": "Quality & Compliance"
  },
  {
    "name": "contacts",
    "description": "Contact management — agents, humans, addresses, handles, relationships, interaction history",
    "tags": [
      "crm",
      "network",
      "data"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 60,
    "category": "Other"
  },
  {
    "name": "context-review",
    "description": "Audits whether tasks load the right skills context at dispatch time",
    "tags": [
      "infrastructure",
      "monitoring",
      "context"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 120,
    "category": "Quality & Compliance"
  },
  {
    "name": "dao-zero-authority",
    "description": "DAO proposal detection, governance participation, and voting on Stacks",
    "tags": [
      "governance",
      "dao",
      "stacks",
      "voting"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 30,
    "category": "DeFi & Governance"
  },
  {
    "name": "defi-bitflow",
    "description": "Bitflow DEX — DCA automation, swap quotes, and high-spread signal detection",
    "tags": [
      "defi",
      "trading",
      "mainnet-only"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 60,
    "category": "DeFi & Governance"
  },
  {
    "name": "defi-stacks-market",
    "description": "Prediction market trading and intelligence on stacksmarket.app — budget-enforced trading, position tracking, and signal filing. Mainnet-only.",
    "tags": [
      "l2",
      "defi",
      "prediction-markets",
      "mainnet-only",
      "trading"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 360,
    "category": "DeFi & Governance"
  },
  {
    "name": "dev-landing-page-review",
    "description": "Full React/Next.js PR review — 77 performance rules + 10 composition rules + ~100 UI/accessibility rules for aibtcdev/landing-page PRs",
    "tags": [
      "react",
      "nextjs",
      "review",
      "performance",
      "composition",
      "accessibility",
      "ui"
    ],
    "hasSensor": false,
    "hasCli": false,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Development Tools"
  },
  {
    "name": "erc8004-identity",
    "description": "ERC-8004 on-chain agent identity management — register agent identities, update URI and metadata, manage operator approvals, set/unset agent wallet, transfer identity NFTs, and query identity info.",
    "tags": [
      "erc8004",
      "identity",
      "l2",
      "write"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "On-Chain Identity (ERC-8004)"
  },
  {
    "name": "erc8004-reputation",
    "description": "ERC-8004 on-chain agent reputation management — submit and revoke feedback, append responses, approve clients, and query reputation summaries, feedback entries, and client lists.",
    "tags": [
      "erc8004",
      "reputation",
      "l2",
      "write"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "On-Chain Identity (ERC-8004)"
  },
  {
    "name": "erc8004-trust",
    "description": "ERC-8004 trust score aggregation — compute a composite 0-100 trust score for an agent by combining on-chain reputation feedback and validation scores.",
    "tags": [
      "erc8004",
      "reputation",
      "validation",
      "read-only"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": null,
    "category": "On-Chain Identity (ERC-8004)"
  },
  {
    "name": "erc8004-validation",
    "description": "ERC-8004 on-chain agent validation management — request and respond to validations, and query validation status, summaries, and paginated lists by agent or validator.",
    "tags": [
      "erc8004",
      "validation",
      "l2",
      "write"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "On-Chain Identity (ERC-8004)"
  },
  {
    "name": "github-ci-status",
    "description": "Monitors GitHub Actions CI runs on our PRs and detects failures",
    "tags": [
      "sensor",
      "github",
      "ci"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 15,
    "category": "GitHub & DevOps"
  },
  {
    "name": "github-issue-monitor",
    "description": "Monitors GitHub issues on managed and collaborative repos, creates triage tasks with org maintainer context",
    "tags": [
      "sensor",
      "github"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 15,
    "category": "GitHub & DevOps"
  },
  {
    "name": "github-mentions",
    "description": "Detects GitHub notifications and engages as org maintainer across managed and collaborative repos",
    "tags": [
      "sensor",
      "github"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 5,
    "category": "GitHub & DevOps"
  },
  {
    "name": "github-release-watcher",
    "description": "Detects new releases on bun, claude-code, stacks-core, aibtcdev/skills and 5 other watched repos — creates P7 review tasks",
    "tags": [
      "monitoring",
      "github",
      "ecosystem"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 60,
    "category": "GitHub & DevOps"
  },
  {
    "name": "github-security-alerts",
    "description": "Monitor Dependabot security alerts on managed repos — P3/P4 alerts for critical/high CVEs",
    "tags": [
      "security",
      "github",
      "monitoring"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 360,
    "category": "GitHub & DevOps"
  },
  {
    "name": "github-worker-logs",
    "description": "Sync worker-logs forks, monitor production events, report trends",
    "tags": [
      "monitoring",
      "infrastructure",
      "sync"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 360,
    "category": "GitHub & DevOps"
  },
  {
    "name": "quest-create",
    "description": "Decompose complex tasks into sequential phases with checkpoint-based idempotent execution",
    "tags": [
      "orchestration",
      "decomposition",
      "planning"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Other"
  },
  {
    "name": "social-agent-engagement",
    "description": "Proactive outreach to AIBTC network agents for collaboration on shared interests",
    "tags": [
      "comms",
      "collaboration",
      "aibtc"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 60,
    "category": "Publishing & Social"
  },
  {
    "name": "social-x-ecosystem",
    "description": "Monitor X for ecosystem keywords (Bitcoin, Stacks, AIBTC, Claude Code, etc.) and file research tasks for high-signal tweets",
    "tags": [
      "social",
      "research",
      "x"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 15,
    "category": "Publishing & Social"
  },
  {
    "name": "social-x-posting",
    "description": "Post tweets, read timeline, and manage presence on X (Twitter) via API v2",
    "tags": [
      "social",
      "publishing",
      "x"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 15,
    "category": "Publishing & Social"
  },
  {
    "name": "stacks-payments",
    "description": "Watch Stacks blockchain for STX payments to Arc's address and create service tasks from arc: memo codes",
    "tags": [
      "payments",
      "stacks",
      "sensor",
      "monetization"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 3,
    "category": "Bitcoin & Stacks"
  },
  {
    "name": "stacks-stackspot",
    "description": "Autonomous Stacking participation — detect joinable pots, auto-join with Arc wallet, claim sBTC rewards. Mainnet-only lottery stacking.",
    "tags": [
      "l2",
      "stacking",
      "mainnet-only",
      "autonomous"
    ],
    "hasSensor": true,
    "hasCli": false,
    "hasAgent": false,
    "sensorInterval": 7,
    "category": "Bitcoin & Stacks"
  },
  {
    "name": "styx",
    "description": "BTC→sBTC conversion via Styx protocol (btc2sbtc.com) — pool status, fees, deposit, and tracking",
    "tags": [
      "defi",
      "bitcoin",
      "sbtc"
    ],
    "hasSensor": false,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": null,
    "category": "Other"
  },
  {
    "name": "worker-deploy",
    "description": "Auto-deploy arc0btc-worker to Cloudflare Workers on code changes",
    "tags": [
      "deployment",
      "cloudflare",
      "worker"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": false,
    "sensorInterval": 5,
    "category": "Other"
  },
  {
    "name": "worker-logs-monitor",
    "description": "Query worker-logs instances for errors, cross-reference GitHub issues, file new issues",
    "tags": [
      "monitoring",
      "infrastructure",
      "logs"
    ],
    "hasSensor": true,
    "hasCli": true,
    "hasAgent": true,
    "sensorInterval": 60,
    "category": "Other"
  }
] as const;

export const GET: APIRoute = () => {
  return new Response(JSON.stringify(catalog, null, 2), {
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600",
    },
  });
};

export const prerender = true;
