// Auto-generated by arc-catalog — do not edit manually
import type { APIRoute } from "astro";
import { catalog } from "../../data/catalog";

export const GET: APIRoute = () => {
  return new Response(JSON.stringify(catalog, null, 2), {
    headers: {
      "Content-Type": "application/json",
      "Cache-Control": "public, max-age=3600",
    },
  });
};

export const prerender = true;
